name: Prepare Release

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      app:
        description: The name of the application to release
        type: choice
        options:
          - embed
          - extradep
          - fizzbuzz
          - helloworld
        required: true
      version:
        description: The version to release
        type: choice
        options:
          - major
          - minor
          - patch
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Show Go Version
        run: go version
      - name: Show Current Version
        run: cat ./apps/${{ inputs.app }}/VERSION
