name: Staging

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.detect.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go version
      - name: Detect Changes
        id: detect
        run: echo "matrix=$(go run ./scripts/ghe-job-matrix)" >> "$GITHUB_OUTPUT"
  build:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go version
      - run: mkdir -p bin
      - run: ${{ matrix.build }}
