name: Staging

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.detect.outputs.has_changes }}
      matrix: ${{ steps.detect.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v5
      - run: go version
      - name: Detect Changes
        id: detect
        run: |
          set -e
          targets=$(go run ./monorepo/cmd/gha-job-matrix)
          echo "matrix={\"target\":$targets}" >> "$GITHUB_OUTPUT"
          if [ "$targets" = "[]" ]; then
            echo "No changes detected."
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          else
            echo "Changes detected: $targets"
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          fi
  build:
    needs: detect-changes
    if: needs.detect-changes.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go version
      - run: mkdir -p bin
      - run: ${{ matrix.target.build }}
